FineUploader/fine-uploader

- client/js/azure/uploader.basic.js
Fix for #1479: Blobs with uuid mode get .undefined extension if original filename has no extension
> Fix for #1479: Blobs uploaded via Azure module with uuid mode get .undefined extension if original filename has no extension

- client/js/s3/util.js
This addresses Widen/fine-uploader#1214 and adds support for a predefined list of headers which are appropriate for S3 without the x-amz-meta- prefix. Documentation may need a stronger notice about checking these as well. (Cr35/IE9)
> Add unprefixed S3 request headers support

- README.md
- client/js/util.js
- client/js/version.js
- docs/browser-support.jmd
- docs/features/chunking.jmd
- docs/features/styling.jmd
- package.json
- test/dev/handlers/composer.json
- test/unit/scaling.js
This irons out issues with file dropping in Edge and updates docs to indicate support. It is initially scheduled as the only change in 5.7.0.
Original issue for Edge support is #1422.
> Microsoft Edge support

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE
This is an attempt to move CLA signing to clahub.com. This failed a year or so ago, but the project has changed now and is actively maintained. The benefit of using clahub.com is that it ensure CLA signers are maintained in a central location and are not modifiable. The previous approach which requires the contributor to sign in a PR was flawed in that the contributor could, at any time, edit their PR comment/description to revoke this agreement without any good audit trail.
> docs(contributing): attempt to re-integrate clahub.com

- Gruntfile.js
- README.md
- client/js/image-support/scaler.js
- client/js/s3/request-signer.js
- client/js/third-party/ExifRestorer.js
- client/js/third-party/crypto-js/core.js
- client/js/third-party/crypto-js/enc-base64.js
- client/js/third-party/crypto-js/hmac.js
- client/js/third-party/crypto-js/lib-typedarrays.js
- client/js/third-party/crypto-js/sha1.js
- client/js/third-party/crypto-js/sha256.js
- client/js/version.js
- docs/features/forms.jmd
- docs/features/modules.jmd
- docs/features/styling.jmd
- docs/quickstart/01-getting-started.jmd
- docs/quickstart/02-setting_options-azure.jmd
- docs/quickstart/02-setting_options-s3.jmd
- docs/quickstart/02-setting_options.jmd
- lib/commonJs/all.js
- lib/commonJs/azure.js
- lib/commonJs/jquery/azure.js
- lib/commonJs/jquery/s3.js
- lib/commonJs/jquery/traditional.js
- lib/commonJs/s3.js
- lib/commonJs/traditional.js
- lib/grunt/configs/concat.js
- lib/grunt/tasks/release.js
- package.json
> CommonJS + AMD support

- client/js/uploader.basic.api.js
Fixed a problem with the CORS request for session not working correctly.
More detailed explanation:
From [the docs](http://docs.fineuploader.com/branch/master/features/CORS.html):
> If you set the `cors.expected` property to true, it is assumed that all requests will be cross-domain requests
This PR addresses a problem that seems to have been introduced in [this commit](https://github.com/FineUploader/fine-uploader/commit/f40705a91ac22244b4b0ca1acbfa11391b680f0c). On [L1634 of uploader.basic.api.js](https://github.com/FineUploader/fine-uploader/blob/d23eaf371a6170c7f468b0df86ce5a6585094854/client/js/uploader.basic.api.js#L1634), the options for the Session requester are extended as such:
```js
qq.extend(options, this._options.cors);
```
Making the session request (calling …
> fix(session): Fixed a problem with the session requester cors request

- client/js/image-support/image.js
I fixed a problem where the if the thumbnail url returned from the server contained a query string, the image type defaults to jpeg, thus breaking any other file type previews
Chrome on OS X
Yes
Yes
> fix(image): Fixed a problem where image previews weren't being loaded

- client/js/azure/uploader.basic.js
Added the `customHeaders` in the options for the getSas() method of delete function. Headers are retrieved from the `signature` attribute.
Ref: https://github.com/FineUploader/fine-uploader/issues/1661
Safari 9.1.2 OSX 10.11.6
Yes
Yes
> Issue 1661 - CustomHeaders not set on delete feature

- client/js/s3/request-signer.js
If signing a file for s3 upload fails FineUploader hangs. Promises related to signing were not calling failure on their parent promises.
Repo steps:
1. Find a large file.
2. Put it in an SD card.
3. Add the file to FineUploader
4. Pull out SD card before the signing can finish.
5. Signing methods fail, rejecting their promise.
6. Promise rejection is not propagated up.
Windows 10. Chrome
Yes
Yes. Develop.
> Reject the signing promises on failure.

- client/typescript/fine-uploader.d.ts
My env was complaining about implicit any.
Added return type to a typescript method definition.
> Add missing return definition

- client/typescript/fine-uploader.d.ts
This updates the S3 and Azure properties to be optional in the typescript definition file for properties with default values.
> Update S3/Azure TypeScript definition file

- README.md
- package.json
This will automatically show the latest backers and sponsors on the README with a link to their respective website. For an example: https://github.com/developit/preact
> Added Open Collective to README.md and in npm postinstall

- client/typescript/fine-uploader.d.ts
Brief description of the changes
extraButtons in typescript define not correct. Due to document, this option allow an array of ExtraButtonsOptions
What browsers and operating systems have you tested these changes on?
NA
Have you written unit tests? If not, explain why.
NA
> Fix extraButtons typescript define not correct

- docs/quickstart/01-getting-started.jmd
This fix will resolve #1930 documentation issue.
Please note that this PR does not want to hijack someone else's efforts. Feel free to close this if this does not feel right.
The change is for documentation.
The change is for documentation.
> Fixes #1930 documentation issue

- client/js/templating.js
- test/unit/templating.js
When adding new rows to a table, the existing mechanism of storing the HTML of a row in variable breaks at least on firefox: When parsing this HTML fragment and creating DOM elements, the browser will ignore tags it does not expect without proper parent tags. Appending this modified DOM branch to the table results in broken DOM structure. Cloning the DOM branch of a row and appending this clone to the table works just fine.
Fixes #1246
Firefox on Ubuntu
Yes
> fix(templating): correctly handle tables

- Makefile
`make setup-dist` failed because `client/commonjs` could not be found
Linux
No
> corrected case of `client/commonJs`

- docs/endpoint_handlers/azure.jmd
Minor edit to get the docs to match the code on the SAS request params.  HOWEVER, we might consider changing the code instead of, or in addition to this PR.  Seems kinda odd to have one variable with an underscore, and the others without:  `_method`, `bloburi`, `qqtimestamp`.
> bloburi param in doc now matches code

- client/js/templating.js
- test/unit/templating.js
Fix for #1945. Calling render resulted in duplicate template renders in the container.  This bug was introduced in the 5.15.3 release due to a change whereby templates renders are now appended to the container instead of replacing the innerHTML.
PR includes a simple unit test to verify calling render no longer results in duplicate contents.
> fix(templating.js): reset caused duplicate template contents (#1945)

- client/js/dnd.js
- client/js/version.js
- package.json
- test/unit/dnd.js
Fixes reported path (qqpath) in case when the file name in question appears in one of its parent directory names, see #1976. The original code used indexOf so if the first occurrence was not a file name itself, it stripped way too much from the path.
Chrome 64.0.3282.167, FF 58.0.2, Edge 41.16299.248.0
Unit tests are present, both for normal case where I used the value the current code returns as a reference, and for the case when directory name is the same as the file name.
> Fix reported path when file name also occurs in parent directory name(s)

- client/js/s3/request-signer.js
- client/js/session.ajax.requester.js
- client/js/traditional/traditional.xhr.upload.handler.js
- client/js/upload-handler/form.upload.handler.js
- client/js/uploadsuccess.ajax.requester.js
- client/js/util.js
- test/unit/util.js
Currently `eval()` is only used for IE7 and prevents sites from implementing content security policies.
Refs #1438, #1529
> refactor: use native JSON.parse, drops IE7 support

- client/js/image-support/megapix-image.js
This PR checks that the `onload` function is defined before calling it. This removes the `Uncaught TypeError: target.onload is not a function` console error while img preview.
Chrome 69.0.3497.100 on MacOS Sierra 10.13.6
No, because the modified code is likely already tested.
> Call target.onload() only when defined
